### ISSUE TITLE
Unable to complete install

### ISSUE THREAD

**Issue by Shonke** [akinazuki/google_aas_et_generate#1]
```shell
# go install
../go/pkg/mod/github.com/89z/rosso@v1.50.2/crypto/crypto.go:7:4: found packages tls (alert.go) and main (generate_cert.go) in /root/go/pkg/mod/github.com/refraction-networking/utls@v1.2.0
```

**Comment by akinazuki** [comment]
unable to reappear on go version go1.18.1 linux/arm64 (ubuntu:jammy)
<img width="1052" alt="image" src="https://user-images.githubusercontent.com/43605695/207264904-79394fa1-73a6-46f4-afaa-f0a678e0f6dd.png">

**Comment by Shonke** [comment]
The problem has been solved.
use golang 1.18.1
