### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by dep4** [akinazuki/google_aas_et_generate#2]
https://github.com/89z/rosso repository was deleted so unable to build. If you have a local copy, please create a repository and push to it? License allows it.

**Comment by akinazuki** [comment]
I have the source code in my `~/go/pkg/mod/github.com/89z/rosso@v1.50.2/`, but i haven't test it yet

[v1.50.2.zip](https://github.com/akinazuki/google_aas_et_generate/files/10329772/v1.50.2.zip)

**Comment by dep4** [comment]
Thank you!!!! I put it here https://github.com/dep4/rosso and was able to build
